service: lab-serverless-aws-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
          Resource:
            - arn:aws:dynamodb:us-east-1:615288673645:table/TableServerlessLab

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events:
      - httpApi:
          path: /item
          method: post
  getAllItems:
    handler: src/getAllItems.handler
    events:
      - httpApi:
          path: /items
          method: get
  getItem:
    handler: src/getItem.handler
    events: 
      - httpApi:
          path: /items/{id}
          method: get
  updateItem:
    handler: src/updateItem.handler
    events:
      - httpApi:
          path: /items/{id}
          method: put

resources:
  Resources:
    TableServerlessLab:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TableServerlessLab
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH